version: 2.1

workflows:
  olx-sre-nd-block1-lesson3-point15-sharing-files:
    jobs:
      - save_hello_world_output

jobs:
  save_hello_world_output:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: "echo to a file in a workspace"
          command: 
            echo "text to output here" > output.txt
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - output.txt
  print_output_file:
    docker:
      - image: cimg/base:stable    
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: "read from file file in workspace"
          command: 
            cat /tmp/workspace/output.txt